In [2]:
import tensorflow as tf
import numpy as np

# Linear Regression

$
\begin{equation}
y = W \cdot x + b
\end{equation}
$

Given some data points and their labels, we can learn the parameters (W and b) of the model by reducing the loss.

The answer of this model's parameters are:  
W_ans = [[3, 5]]  
b_ans = [7] 

In [3]:
# data & label
data = np.array([[2, 6], [1, 2], [4, 5], [6, 8]])
label = np.array([[43], [20], [44], [65]])

## Build the graph (define your model)

In [4]:
[batch_size, data_dim] = data.shape
# reserve place for x and y by placeholder
x = tf.placeholder(tf.float32, [batch_size, data_dim])
y = tf.placeholder(tf.float32, [batch_size, 1])

# W and b are random initialized
W = tf.Variable(tf.random_uniform([data_dim, 1], -1, 1))
b = tf.Variable(tf.random_uniform([1], -1, 1))

# y = w*x+b
y_pred = tf.add(tf.matmul(x, W), b)

# compute the loss
loss = tf.reduce_mean(tf.square(y-y_pred))

# declare an optimizer
opt = tf.train.AdamOptimizer(learning_rate=1).minimize(loss)

## Training and Testing

In [37]:
# create a session
sess = tf.Session()
# initialize variables
sess.run(tf.initialize_all_variables())

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [38]:
def print_params(sess):
    param_w, param_b  = sess.run([W, b])
    print('W =')
    print(param_w)
    print('b =')
    print(param_b)


In [39]:
# feed the data, and run the session
# let's evaluate before training
pred, loss_val = sess.run([y_pred, loss], feed_dict={x: data, y: label})                                                                                                                                     
print('Before training, loss = {}'.format(loss_val))
print('Prediction:')
print(pred)
print_params(sess)

# training parameters (W & b)
max_iter = 200
show_iter = 20
print('Training ...')
for i in range(1, max_iter+1):
    pred, loss_val, _ = sess.run([y_pred, loss, opt], feed_dict={x: data, y: label})
    
    if i%show_iter == 0:
        print('Iter: {} loss: {}'.format(i, loss_val))

print('Training is done.')
print('Prediction:')
print(pred)
print_params(sess)


Before training, loss = 2050.5234375
Prediction:
[[ 0.10971522]
 [ 0.31419683]
 [ 0.75460267]
 [ 0.93111205]]
W =
[[ 0.26389647]
 [-0.11709452]]
b =
[ 0.28448939]
Training ...
Iter: 20 loss: 56.2125587463
Iter: 40 loss: 2.9620950222
Iter: 60 loss: 1.32308363914
Iter: 80 loss: 0.156150564551
Iter: 100 loss: 0.0206669103354
Iter: 120 loss: 0.00856634601951
Iter: 140 loss: 0.00138573534787
Iter: 160 loss: 0.000718749128282
Iter: 180 loss: 0.000287723902147
Iter: 200 loss: 0.000123188743601
Training is done.
Prediction:
[[ 42.98777771]
 [ 20.01573563]
 [ 44.00854111]
 [ 64.995224  ]]
W =
[[ 3.00605559]
 [ 4.99170017]]
b =
[ 7.02607918]
